// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrackToPlaylist(arg1, arg2) {
  return window['go']['backend']['App']['AddTrackToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['backend']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['backend']['App']['DeletePlaylist'](arg1);
}

export function DownloadFromSoundCloud(arg1) {
  return window['go']['backend']['App']['DownloadFromSoundCloud'](arg1);
}

export function GetMusicDir() {
  return window['go']['backend']['App']['GetMusicDir']();
}

export function GetPlaylists() {
  return window['go']['backend']['App']['GetPlaylists']();
}

export function GetPosition(arg1) {
  return window['go']['backend']['App']['GetPosition'](arg1);
}

export function GetSpectrum(arg1) {
  return window['go']['backend']['App']['GetSpectrum'](arg1);
}

export function IsPlaying(arg1) {
  return window['go']['backend']['App']['IsPlaying'](arg1);
}

export function LoadTrack(arg1, arg2) {
  return window['go']['backend']['App']['LoadTrack'](arg1, arg2);
}

export function LogFromJS(arg1, arg2) {
  return window['go']['backend']['App']['LogFromJS'](arg1, arg2);
}

export function OpenMusicDir() {
  return window['go']['backend']['App']['OpenMusicDir']();
}

export function Pause(arg1) {
  return window['go']['backend']['App']['Pause'](arg1);
}

export function Play(arg1) {
  return window['go']['backend']['App']['Play'](arg1);
}

export function RemoveTrackFromPlaylist(arg1, arg2) {
  return window['go']['backend']['App']['RemoveTrackFromPlaylist'](arg1, arg2);
}

export function SavePlaylists(arg1) {
  return window['go']['backend']['App']['SavePlaylists'](arg1);
}

export function ScanMusicDir() {
  return window['go']['backend']['App']['ScanMusicDir']();
}

export function SearchSoundCloud(arg1) {
  return window['go']['backend']['App']['SearchSoundCloud'](arg1);
}

export function Seek(arg1, arg2) {
  return window['go']['backend']['App']['Seek'](arg1, arg2);
}

export function SelectAudioFile() {
  return window['go']['backend']['App']['SelectAudioFile']();
}

export function SetCrossfadeDuration(arg1) {
  return window['go']['backend']['App']['SetCrossfadeDuration'](arg1);
}

export function SetPitch(arg1, arg2) {
  return window['go']['backend']['App']['SetPitch'](arg1, arg2);
}

export function SetTempo(arg1, arg2) {
  return window['go']['backend']['App']['SetTempo'](arg1, arg2);
}

export function SetVolume(arg1, arg2) {
  return window['go']['backend']['App']['SetVolume'](arg1, arg2);
}

export function ToggleAutoMix(arg1) {
  return window['go']['backend']['App']['ToggleAutoMix'](arg1);
}
