// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTrackToPlaylist(arg1:string,arg2:string):Promise<void>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DownloadFromSoundCloud(arg1:string):Promise<void>;

export function GetMusicDir():Promise<string>;

export function GetPlaylists():Promise<Array<main.Playlist>>;

export function GetPosition(arg1:number):Promise<number>;

export function GetSpectrum(arg1:number):Promise<Array<number>>;

export function IsPlaying(arg1:number):Promise<boolean>;

export function LoadTrack(arg1:number,arg2:string):Promise<main.TrackMetadata>;

export function LogFromJS(arg1:string,arg2:string):Promise<void>;

export function OpenMusicDir():Promise<void>;

export function Pause(arg1:number):Promise<void>;

export function Play(arg1:number):Promise<void>;

export function RemoveTrackFromPlaylist(arg1:string,arg2:string):Promise<void>;

export function SavePlaylists(arg1:Array<main.Playlist>):Promise<void>;

export function SearchSoundCloud(arg1:string):Promise<Array<main.SoundCloudResult>>;

export function ScanMusicDir():Promise<Array<main.TrackMetadata>>;

export function Seek(arg1:number,arg2:number):Promise<void>;

export function SelectAudioFile():Promise<string>;

export function SetCrossfadeDuration(arg1:number):Promise<void>;

export function SetPitch(arg1:number,arg2:number):Promise<void>;

export function SetTempo(arg1:number,arg2:number):Promise<void>;

export function SetVolume(arg1:number,arg2:number):Promise<void>;

export function ToggleAutoMix(arg1:boolean):Promise<void>;
