// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMusicDir() {
  return window['go']['main']['App']['GetMusicDir']();
}

export function GetPosition(arg1) {
  return window['go']['main']['App']['GetPosition'](arg1);
}

export function IsPlaying(arg1) {
  return window['go']['main']['App']['IsPlaying'](arg1);
}

export function LoadTrack(arg1, arg2) {
  return window['go']['main']['App']['LoadTrack'](arg1, arg2);
}

export function LogFromJS(arg1, arg2) {
  return window['go']['main']['App']['LogFromJS'](arg1, arg2);
}

export function OpenMusicDir() {
  return window['go']['main']['App']['OpenMusicDir']();
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function ScanMusicDir() {
  return window['go']['main']['App']['ScanMusicDir']();
}

export function Seek(arg1, arg2) {
  return window['go']['main']['App']['Seek'](arg1, arg2);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SetCrossfadeDuration(arg1) {
  return window['go']['main']['App']['SetCrossfadeDuration'](arg1);
}

export function SetPitch(arg1, arg2) {
  return window['go']['main']['App']['SetPitch'](arg1, arg2);
}

export function SetTempo(arg1, arg2) {
  return window['go']['main']['App']['SetTempo'](arg1, arg2);
}

export function SetVolume(arg1, arg2) {
  return window['go']['main']['App']['SetVolume'](arg1, arg2);
}

export function ToggleAutoMix(arg1) {
  return window['go']['main']['App']['ToggleAutoMix'](arg1);
}
